language: go

before_script:
  - go get github.com/davecgh/go-spew/spew
  - go get github.com/stretchr/testify/require
  - go get github.com/tools/godep

script:
  - make test

go:
  - 1.2
  - 1.3
  - 1.4
  - tip